import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

/**
 * Generates a clean, professional PDF report of job application conversion metrics.
 *
 * @param {object} reportData - Metrics data generated by reportDataService
 * @param {string} outputPath - Target file path on disk
 * @returns {Promise<string>} - Resolves with outputPath when write stream completes
 */
export function generateReportPDF(reportData, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      // Ensure target directory exists
      const outputDir = path.dirname(outputPath);
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
      });

      const writeStream = fs.createWriteStream(outputPath);
      doc.pipe(writeStream);

      // --- COLOR PALETTE & STYLES ---
      const primaryColor = '#1e293b'; // Slate 800
      const brandColor = '#2563eb';   // Indigo / Blue 600
      const accentColor = '#059669';  // Emerald 600
      const grayColor = '#64748b';    // Slate 500
      const borderColor = '#e2e8f0';  // Slate 200
      const warningColor = '#d97706'; // Amber 600

      // --- HEADER ---
      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .fillColor(brandColor)
        .text('JOB APPLICATION TRUTH TRACKER', { align: 'left' });

      doc
        .fontSize(14)
        .font('Helvetica')
        .fillColor(primaryColor)
        .text('Executive Funnel & Conversion Report', { align: 'left' })
        .moveDown(0.25);

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor(grayColor)
        .text(`Report Period: ${reportData.period_start} to ${reportData.period_end}  |  Generated: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`)
        .moveDown(1);

      // Divider Line
      doc
        .strokeColor(borderColor)
        .lineWidth(1)
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke()
        .moveDown(1);

      // --- SECTION 1: EXECUTIVE SUMMARY NUMBERS ---
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor(primaryColor)
        .text('1. Executive Funnel Summary')
        .moveDown(0.5);

      const summary = reportData.summary || {};
      const startY = doc.y;

      // Summary Box
      doc
        .rect(50, startY, 495, 70)
        .fillAndStroke('#f8fafc', borderColor);

      doc.fillColor(primaryColor);

      // 4 Metric Columns
      const colWidth = 495 / 4;

      // Col 1: Total Applications
      doc
        .fontSize(18)
        .font('Helvetica-Bold')
        .fillColor(primaryColor)
        .text(`${summary.total_applications || 0}`, 50, startY + 15, { width: colWidth, align: 'center' });
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor(grayColor)
        .text('TOTAL APPS', 50, startY + 42, { width: colWidth, align: 'center' });

      // Col 2: Response Rate
      doc
        .fontSize(18)
        .font('Helvetica-Bold')
        .fillColor(accentColor)
        .text(`${summary.response_rate || 0}%`, 50 + colWidth, startY + 15, { width: colWidth, align: 'center' });
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor(grayColor)
        .text('RESPONSE RATE', 50 + colWidth, startY + 42, { width: colWidth, align: 'center' });

      // Col 3: Rejection Rate
      doc
        .fontSize(18)
        .font('Helvetica-Bold')
        .fillColor('#dc2626')
        .text(`${summary.rejection_rate || 0}%`, 50 + colWidth * 2, startY + 15, { width: colWidth, align: 'center' });
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor(grayColor)
        .text('REJECTION RATE', 50 + colWidth * 2, startY + 42, { width: colWidth, align: 'center' });

      // Col 4: Ghosted Rate
      doc
        .fontSize(18)
        .font('Helvetica-Bold')
        .fillColor(warningColor)
        .text(`${summary.ghosted_rate || 0}%`, 50 + colWidth * 3, startY + 15, { width: colWidth, align: 'center' });
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor(grayColor)
        .text('GHOSTED RATE', 50 + colWidth * 3, startY + 42, { width: colWidth, align: 'center' });

      doc.y = startY + 85;

      // --- SECTION 2: RESPONSE RATE BY RESUME VARIANT ---
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor(primaryColor)
        .text('2. Response Rate by Resume Variant (10x Insight)')
        .moveDown(0.2);

      doc
        .fontSize(9)
        .font('Helvetica-Oblique')
        .fillColor(grayColor)
        .text('Ranked from highest converting to lowest converting resume variation.')
        .moveDown(0.5);

      if (!reportData.resumes || reportData.resumes.length === 0) {
        doc
          .fontSize(10)
          .font('Helvetica')
          .fillColor(grayColor)
          .text('No resume data recorded during this period.')
          .moveDown(1);
      } else {
        let hasLowSampleResume = false;

        reportData.resumes.forEach((r, idx) => {
          if (r.low_sample_size) hasLowSampleResume = true;

          const isTopPerformer = idx === 0 && r.response_rate > 0;
          const bulletColor = isTopPerformer ? accentColor : primaryColor;

          doc
            .fontSize(10)
            .font('Helvetica-Bold')
            .fillColor(bulletColor)
            .text(`• ${r.name}: `, { continued: true })
            .font('Helvetica')
            .fillColor(primaryColor)
            .text(`${r.response_rate}% response rate `, { continued: true })
            .fillColor(grayColor)
            .text(`(${r.responses} responses / ${r.total} applications, ${r.ghosted} ghosted, ${r.rejections} rejections)${r.low_sample_size ? ' *' : ''}`)
            .moveDown(0.3);
        });

        if (hasLowSampleResume) {
          doc
            .moveDown(0.2)
            .fontSize(8)
            .font('Helvetica-Oblique')
            .fillColor(warningColor)
            .text('* Note: Sample size is currently fewer than 3 applications. Statistical confidence will improve with additional submissions.')
            .moveDown(0.8);
        } else {
          doc.moveDown(0.8);
        }
      }

      // --- SECTION 3: RESPONSE RATE BY PLATFORM ---
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor(primaryColor)
        .text('3. Response Rate by Application Platform')
        .moveDown(0.2);

      doc
        .fontSize(9)
        .font('Helvetica-Oblique')
        .fillColor(grayColor)
        .text('Channel conversion efficiency ranked by response fidelity.')
        .moveDown(0.5);

      if (!reportData.platforms || reportData.platforms.length === 0) {
        doc
          .fontSize(10)
          .font('Helvetica')
          .fillColor(grayColor)
          .text('No platform data recorded during this period.')
          .moveDown(1);
      } else {
        reportData.platforms.forEach((p) => {
          doc
            .fontSize(10)
            .font('Helvetica-Bold')
            .fillColor(primaryColor)
            .text(`• ${p.platform.toUpperCase()}: `, { continued: true })
            .font('Helvetica')
            .fillColor(accentColor)
            .text(`${p.response_rate}% response `, { continued: true })
            .font('Helvetica')
            .fillColor(grayColor)
            .text(`(${p.responses} responses / ${p.total} applications)`)
            .moveDown(0.3);
        });
        doc.moveDown(1);
      }

      // --- FOOTER & HONEST TRUTH ASSESSMENT ---
      doc
        .strokeColor(borderColor)
        .lineWidth(1)
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke()
        .moveDown(0.8);

      doc
        .fontSize(10)
        .font('Helvetica-Bold')
        .fillColor(brandColor)
        .text('Truth Tracker Advisory:')
        .font('Helvetica')
        .fontSize(9)
        .fillColor(grayColor)
        .text('Focus your effort on high-converting resume variants and platforms. If an application channel exhibits elevated ghosting rates, consider direct outreach or tailored keyword alignment before submitting further.', { align: 'justify' });

      doc.end();

      writeStream.on('finish', () => resolve(outputPath));
      writeStream.on('error', (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
}

export default {
  generateReportPDF,
};
